import { configureStore } from "@reduxjs/toolkit";
import cartReducer from "./components/cartSlice";

export type RootState = ReturnType<typeof store.getState>;
// Define the AppDispatch type
export type AppDispatch = typeof store.dispatch;

// Configure the store with the cartReducer
export const store = configureStore({
  reducer: {
    // This now refers to the reducer generated by createSlice
    cart: cartReducer,
  },
});
